server:
  port: 8080

spring:
  application:
    name: consumer-demo

eureka:
  client:
    service-url:
      defaultZone : http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/
zuul:
  host:
    # 代理普通的http请求超时时长
    connect-timeout-millis: 2000
    # socket超时
    socket-timeout-millis: 10000
    # http连接池大小
    max-total-connections: 200
    # 每个host最大连接数
    max-per-route-connections: 20
  # 信号量模式
  ribbon-isolation-strategy: semaphore
  semaphore:
    # 最大信号量
    max-semaphores: 100
  # 路由代理
  routes:
    route1:
      path: /narito/q/**
      url: http://localhost:8001
    route2:
      path: /narito/w/**
      serviceId: helloserver
